django/parbatcms/formentry/urls.py
from django.conf.urls import url
from django.urls import path

from . import views
from . import formviews

urlpatterns = [
    # url(r'^$', views.index, name='index'),
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    url(r'^datamode/$', views.entry, name='entry'),
    # url(r'^datamode/<int:person>/person/(?P<house>[0-9]+)/$', views.entry, name='personid'),
    path('datamode/<int:person>/person/', views.entry, name='personid'),
    url(r'^people/$', views.all_people, name='people'),
    # url(r'^(?P<person_id>[0-9]+)/$', views.detail, name='detail'),
        path('people/<int:status>/stat/', views.all_people, name='people_status'),
        

    path('geo/<int:id>/', views.geo_entry, name='geo'),
        path('house/<int:geo>/<int:pid>/house/',views.house_entry, name='house_entry'),
            path('house/<int:coordinates>/<int:pid>/head/', views.house_head_entry, name='house_head'),
        path('family/<int:house>/<int:fid>/family/<int:geo>/coordinates/<int:pid>/person', views.family_entry, name='family_details'),
        path('relation/<int:mooli>/<int:child>/<int:entry>/', views.relation_entry, name='relation'),
    # # path('')

    path('family/<int:geo>/coordinate/',views.family_list,name='family_list'),
    path('family/<int:family_id>/members', views.member_list, name="memberlist"),

    path('myform/<int:form_id>/member/<int:member>/marktype/<int:mark>/<int:marker>/', formviews.mainforms, name='form_basic'),
    path('myform/all_forms', formviews.all_my_forms, name='all_my_forms'),
    path('userforms/<int:member>/type/<int:memtype>', formviews.all_member_forms, name='memberforms'),
        path('deleteform/<int:form_id>/member/<int:member>/marktype/<int:mark>/<int:marker>/', formviews.deleteforms, name='deleteforms'),
        path('printform/<int:form_id>/member/<int:member>/marktype/<int:mark>/<int:marker>/', formviews.printforms, name='printforms'),
        path('myform/print_forms', formviews.print_my_forms, name='print_my_forms'),
        path('myform/delete_forms', formviews.delete_my_forms, name='delete_my_forms'),
        path('delete/<int:id>/type/<int:del_type>/', formviews.deleteEntry, name='delete_entry'),

    url(r'^design/$', formviews.index, name='form_index'),
    path('design/<int:id>/main/', formviews.formindex, name='submit_formindex'),
    path('design/<int:id>/table/', formviews.tableindex, name='table_index'),
    path('design/<int:formid>/form/<int:tid>/mytable/', formviews.submit_tableindex, name='submit_tableindex'),
    path('design/<int:id>/question/', formviews.questionindex, name='question_index'),
    path('design/<int:tid>/table/<int:qid>/myquestion/', formviews.submit_questionindex, name='submit_questionindex'),
    path('design/<int:id>/choice/', formviews.choiceindex, name='choice_index'),
    path('design/<int:qid>/question/<int:cid>/mychoice/', formviews.submit_choiceindex, name='submit_choiceindex'),

    path('houses/', views.all_my_houses, name='all_my_houses'),

    # moved testing to new app: postform
    # path('design/test', formviews.seePost, name="testing"),

]

#Namespacing URL Names
app_name = "formentry"

django/parbatcms/parbatcms/urls.py
from django.conf.urls import include, url
# from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from formentry import views


urlpatterns = [
    # url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    # url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
    url(r'^personal/', include('personal.urls')),
    url(r'^forms/', include('formentry.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^post/', include('postform.urls')),
    url(r'^$', views.index, name='index'),
    # url(r'^ajax/', include('mydajax.urls')),

]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/parbatcms/polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # url(r'^$', views.index, name='index'),
    # ex: /polls/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

#Namespacing URL Names
app_name = "polls"

django/parbatcms/postform/urls.py
from django.conf.urls import url
from django.urls import path
from photouploads import photoviews
from . import views

urlpatterns = [
    # url(r'^$', views.index, name='index'),
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # url(r'^datamode/$', views.entry, name='entry'),
    path('data', views.makePost, name='saveposts'),
    path('design/test', views.seePost, name="seepost"),
    path('uploads/<int:member>/<int:memberType>', photoviews.simple_upload, name="upload")
]

#Namespacing URL Names
app_name = "postform"

django/parbatcms/formentry/models.py
from django.db import models

# Create your models here.
# from formentry.submodals.formGenerator import *
from formentry.submodals.formGenerator import *

django/parbatcms/formentry/forms.py
from django.forms import ModelForm, DateTimeInput, HiddenInput, Textarea
from personal.models import *

class PersonalForm(ModelForm):
    def __init__(self, *args, **kwargs):
       self.request = kwargs.pop('request', None)
       return super(PersonalForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Personal
        exclude = ['gened']
        fields = '__all__'
        # widgets = {
        #     'name': Textarea(attrs={'cols': 80, 'rows': 20}),
        # }
        field_classes = {
            # 'slug': MySlugFormField,
            'hari':'freaks', 'class':'form-control'
        }
        widgets = {
            'pub_date': DateTimeInput(attrs={'class': 'datetime-input'}),
            'creator' : Textarea(attrs={'disabled':'True'}),
        }


class HouseForm(ModelForm):
    class Meta:
        model = House
        fields = '__all__'

class GeoForm(ModelForm):
    class Meta:
        model = GeoCode
        fields = '__all__'

class FamilyForm(ModelForm):
    class Meta:
        model = Family
        fields = '__all__'

class RelationForm(ModelForm):
    class Meta:
        model = Relation
        fields = '__all__'

django/parbatcms/formentry/views.py
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from django.contrib.auth.decorators import login_required

from .forms import *
from django.http import Http404


# Create your views here.
@login_required(login_url='users:login')
def index(request):
    #2 template = loader.get_template('polls/index.html')
    context = {

    }
    return render(request, 'design/index.html', context)
    #2 return HttpResponse(template.render(context, request))

@login_required(login_url='users:login')
def entry(request, person=0,house=None):
    request.session['myurl'] = request.path

    if person!=0:
        my_person = Personal.objects.get(pk = int(person))
        form = PersonalForm(request.POST or None, instance=my_person)
    else:
        form = PersonalForm(request.POST or None)
    if form.is_valid():
        person_saved = form.save()
        return redirect('formentry:people_status', status=1)
    return render(request, 'design/forms.html',{'form':form, 'user':request.user, 'personid':person, 'houseid':house})

@login_required(login_url='users:login')
def all_people(request, status=0):
    request.session['myurl'] = request.path
    a = Personal.objects.all()
    if status==1:
        status_name = "Saved"
    else:
        status_name = None
    return render(request, 'design/all.html', {'user':request.user,  'status':status_name, 'all':a})


@login_required(login_url='users:login')
def geo_entry(request, id=0):
    request.session['myurl'] = request.path
    if id !=0 :
        my_geo = GeoCode.objects.get(pk=int(id))
        form = GeoForm(request.POST or None, instance=my_geo)
    else:
        form = GeoForm(request.POST or None)
    if form.is_valid():
        geo_saved = form.save()
        return redirect('formentry:house_entry',geo=geo_saved.id, pid=0)
    return render (request,'entry_forms/geo.html',{'form':form, 'geoid':id})

@login_required(login_url='users:login')
def house_entry(request,geo=0, pid=0 ):
    request.session['myurl'] = request.path
    coordinate = GeoCode(pk=geo)
    try:
        my_house = House.objects.get(coordinates=coordinate)
        form = HouseForm(request.POST or None, instance=my_house)
    except House.DoesNotExist:
        if pid ==0:
            return redirect('formentry:family_details', house=0,  fid=0, geo=geo, pid=0)
        owner = Family(id=pid)
        my_house = House(coordinates=coordinate, owner=owner)
        form = HouseForm(request.POST or None, instance=my_house)
    add_others = True
    if form.is_valid():
        house_saved = form.save()
        return redirect('formentry:family_list', geo=geo)
    return render (request, 'entry_forms/house.html', {'form':form, 'personid':pid, 'geoid':geo, 'add_others':add_others})

@login_required(login_url='users:login')
def family_entry(request, house=0, fid=0, geo=0, pid=0):
    #fid = family head
    #pid = family person... if fid doesn't exist pid becomes main head
    request.session['myurl'] = request.path
    if fid==0:
        return redirect('formentry:house_head', coordinates=geo, pid=0)
    try:
        # family_head = Personal(id=fid)
        my_family = Family.objects.get(id=fid)
        # if my_family:
        #     return redirect('formentry:house_head', coordinates=geo, pid=0)
        if (request.POST or None) == None:
            return redirect('formentry:memberlist', family_id=fid)
        form = FamilyForm(request.POST or None, instance=my_family)
    except Family.DoesNotExist:
        family_head = Personal(id=fid)
        my_family = Family(person_head=family_head, myhouse=GeoCode(id=geo))
        form = FamilyForm(request.POST or None, instance=my_family)
    try:
        house_families = Family.objects.filter(myhouse=house)
    except:
        house_families = None
    if form.is_valid():
        family_saved =form.save()
        if house==0:
            return redirect ('formentry:house_entry', geo=geo, pid=family_saved.id)
        else:
            return redirect('formentry:family_details', house=house, fid=fid, geo=geo, pid=pid)
    return render(request, 'entry_forms/family.html',{'form':form, 'families':house_families, 'geo':geo, 'house':house, 'pid':pid, 'fid':fid})

@login_required(login_url='users:login')
def house_head_entry(request,coordinates=0, pid=0):
    request.session['myurl'] = request.path

    if pid != 0:
        my_person = Personal.objects.get(pk = int(pid))
        form = PersonalForm(request.POST or None, instance=my_person)
    else:
        form = PersonalForm(request.POST or None, request=request)
    if form.is_valid():
        person_saved = form.save(commit=False)
        person_saved.creator = request.user.username
        person_saved.save()
        return redirect('formentry:family_details', house=0, fid=person_saved.id, geo=coordinates, pid =0)

    # request.session['myurl'] = request.path
    return render(request, 'entry_forms/user_forms.html',{'form':form, 'user':request.user, 'personid':pid, 'geo':coordinates, 'form_next':'house'})

@login_required(login_url='users:login')
def family_list(request, geo):
    request.session['myurl'] = request.path

    GeoObject = GeoCode.objects.get(pk=geo)
    # request.session['myurl'] = request.path
    ListofFamilies = Family.objects.filter(myhouse=GeoObject)
    return render(request, 'entry_forms/family_list.html',{'families':ListofFamilies, 'geo':geo, 'request':request})


@login_required(login_url='users:login')
def member_list(request, family_id):
    request.session['myurl'] = request.path

    my_family = Family.objects.get(pk=family_id)
    request.session['myurl'] = request.path
    head = my_family.person_head
    try:
        ListofMembers = Relation.objects.filter(family=my_family)
    except Relation.DoesNotExist:
        ListofMembers = {}
    geo = my_family.myhouse.id # To reference back to family from member_list.html
    return render(request, 'entry_forms/family_member_list.html',{'members':ListofMembers, 'mooli':my_family.id, 'geo' : geo , 'head':head })

@login_required(login_url='users:login')
def relation_entry(request,mooli=0,child=0, entry=0):
    request.session['myurl'] = request.path

    try:
        mool_family = Family.objects.get(id=mooli)
        family_child = Personal.objects.get(id=child)
        if entry==0:
            form = PersonalForm(request.POST or None, instance=family_child)
            return render(request, 'entry_forms/user_forms.html',{'form':form, 'user':request.user, 'child':child, 'mooli':mooli, 'flag':'relation', 'personid':child })
    except Personal.DoesNotExist:
        form = PersonalForm(request.POST or None, request=request)
        if form.is_valid():
            # New Entry of PersonalForm
            # form = PersonForm(request.POST or None)
            saved_entry = form.save()
            return redirect('formentry:relation', mooli=mooli, child=saved_entry.id, entry=1)
        return render(request, 'entry_forms/user_forms.html',{'form':form, 'user':request.user, 'mooli':mooli, 'child':child, 'flag':'relation' })

    try:
        my_relation = Relation.objects.get(family=mool_family, person2=family_child)
        form = RelationForm(request.POST or None, instance=my_relation)
    except Relation.DoesNotExist:
        my_relation = Relation(family=mool_family, person2 =family_child)
        form = RelationForm(request.POST or None, instance=my_relation)
    if form.is_valid():
        relation_saved = form.save()
        return redirect('formentry:relation', mooli=mooli,  child=child, entry=0)
    return render(request, 'entry_forms/relation.html',{'form':form, 'mooli':mooli, 'child':child, 'entry':2})

@login_required(login_url='users:login')
def all_my_houses(request):
    request.session['myurl'] = request.path

    Houses = House.objects.all()
    # request.session['myurl'] = request.path
    HouseList = House.objects.all()
    return render(request, 'entry_forms/houselist.html',{'houses':HouseList, 'request':request})

django/parbatcms/formentry/templates/base_forms/allforms.html
{% extends 'entry_forms/user_forms.html' %}
{% load widget_tweaks %}
{% block form-title %}
  <h4 class="card-title">सबै फारमहरु</h4>
  <p class="card-category">यी फारमहरु हेर्नको लागि मात्र हो ।</p>
{% endblock %}

{% block form-body %}
{% for forms in allforms %}
{% with mytype=forms.formType   %}
<p><a href="{% url 'formentry:form_basic' form_id=forms.id member=member mark=mark marker=marker %}" class="btn btn-primary">{{forms}} : Type {{mytype}}</a></p>
{% endwith %}
{% endfor %}
{% endblock %}
{% block form-footer %}

{% endblock %}

{% block form-nav %}
{% if next %}
<a class="btn btn-primary" href="{{next}}">Next</a>
{% endif %}
{% if back %}
<p><a class="btn btn-primary" href="{{back}}">पछाडी</a></p>
{% endif %}
{% if new %}
<a class="btn btn-primary" href="{{new}}">अर्को थप्नुहोस् ।</a>
{% endif %}
<a class="btn btn-danger" href="{% url 'formentry:all_my_forms' %}">सबै फारम हेर्नुहोस् । </a>
{% endblock %}

django/parbatcms/formentry/templates/base_forms/base.html
{% extends 'entry_forms/user_forms.html' %}

{% block form-title %}
  <h4 class="card-title">{{formtitle}}</h4>
  <p class="card-category">{{formdescription}}</p>
{% endblock %}

{% block form-body %}
<form action="{% url %}" method="post">

</form>
<p><a href="{% url 'formentry:family_details' fid=member.id geo=geo pid=0 house=1 %}" class="btn btn-primary">{{member}}</a></p>
{% endblock %}

{% block form-footer %}

{% endblock %}

{% block form-nav %}
<a href="{% url 'formentry:family_details' geo=geo fid=0 pid=0 house=0%}" role="button" class="btn btn-primary">नयाँ परिवार थप्नुहोस् </a>
{% endblock %}

django/parbatcms/formentry/templates/base_forms/deleteform.html
{% extends 'entry_forms/user_forms.html' %}
{% load widget_tweaks %}
{% block form-title %}
  <h4 class="card-title">{{form.formName}}</h4>
  <p class="card-category">जम्मा प्रश्नकर्ता सङ्ख्या =‍ {{form.markers}}</p>
{% endblock %}

{% block form-body %}

<h2><a href="{% url 'formentry:delete_entry' id=form.id del_type=1 %}"> Delete हटाउनुहोस् </a></h2>
{% for tables in formquestions %}
  <p><strong>{{tables.table.tableName}}</strong></p>

  <h5><a href="{% url 'formentry:submit_tableindex' tid=tables.table.id formid=tables.table.formID.id %}">Edit अद्यावद्यिक गर्नुहोस्</a></h5>
  <h5><a href="{% url 'formentry:delete_entry' id=tables.table.id del_type=2 %}"> Delete हटाउनुहोस् </a></h5>
  {% for one_question in tables.table_questions %}
    <div class="form-group row">
      <label style="text-align:right; font-size:18px; text-transform:none;" for="{{one_question.question.id}}" class="col-md-6 col-form-label"><p style="color:red;">{{one_question.question}} {% if mark >= 1 %}</p><p> अङ्क भार: {{one_question.question.marks}} {% endif %}</p></label>
      <div class="col-md-6">
          <h7><a href="{% url 'formentry:submit_questionindex' qid=one_question.question.id tid=tables.table.id %}">Edit अद्यावद्यिक गर्नुहोस्</a></h7>
          <h7><a href="{% url 'formentry:delete_entry' id=one_question.question.id del_type=3 %}"> Delete हटाउनुहोस् </a></h7>
      </div>
      <div class="col-md-12">
        {% if one_question.question.answerType == 'sc' %}
          {% for choices in one_question.choice %}
            <p><a href="{% url 'formentry:delete_entry' id=choices.id del_type=4 %}">{{choices}} हटाउनुहोस् ।</a></p>
            <p><a href="{% url 'formentry:submit_choiceindex' cid=choices.id qid=one_question.question.id %}">{{choices}} Update/अद्यावद्यिक</a></p>
          {% endfor %}
        </select>
        {% endif  %}
      </div>

    </div>


  {% endfor %}

{% endfor %}

{% endblock %}
{% block form-footer %}

{% endblock %}

{% block form-nav %}
{% if next %}
<a class="btn btn-primary" href="{{next}}">Next</a>
{% endif %}
{% if back %}
<p><a class="btn btn-primary" href="{{back}}">पछाडी</a></p>
{% endif %}
{% if new %}
<a class="btn btn-primary" href="{{new}}">अर्को थप्नुहोस् ।</a>
{% endif %}
<a class="btn btn-danger" href="/forms/design/">सबै फारम हेर्नुहोस् । </a>
{% endblock %}

django/parbatcms/formentry/templates/base_forms/design.html
{% extends 'entry_forms/user_forms.html' %}
{% load widget_tweaks %}
{% block form-title %}
  <h4 class="card-title">{{formtitle}}</h4>
  <p class="card-category">{{formdescription}}</p>
{% endblock %}

{% block form-body %}
<form action="{{url}}" method="post">
  {% for field in form %}
    <div class="form-group">
        {{ field.errors }}
        {{ field.label_tag }}
        {% if field.name != 'pub_date' %}
          {{ field |attr:"class:form-control" }}
        {% else %}
          {{ field |attr:"class:datetime-input form-control" }}
        {% endif %}
        {% if field.help_text %}
        <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
    </div>
{% endfor %}
{% csrf_token %}
<input type="submit" name="Submit" value="Submit" class="btn btn-danger">
</form>
{% endblock %}

{% block form-footer %}

{% endblock %}

{% block form-nav %}
{% if next %}
<a class="btn btn-primary" href="{{next}}">Next</a>
{% endif %}
{% if back %}
<p><a class="btn btn-primary" href="{{back}}">पछाडी</a></p>
{% endif %}
{% if new %}
<a class="btn btn-primary" href="{{new}}">अर्को थप्नुहोस् ।</a>
{% endif %}
<a class="btn btn-danger" href="/forms/design/">सबै फारम हेर्नुहोस् । </a>
{% endblock %}

django/parbatcms/formentry/templates/base_forms/list.html
{% extends 'entry_forms/user_forms.html' %}

{% block form-title %}
  <h4 class="card-title">{{formtitle}}</h4>
  <p class="card-category">{{formdescription}}</p>
{% endblock %}



{% block form-body %}
<div id="A">
  {% for member in list %}
  <div id="{{member.id}}">{% if form_type %}
    <a href="{% url 'formentry:submit_formindex' id=member.id %}" class="btn btn-primary">{{member}}</a>
    {% endif %}
    {% if tab_type %}
    <a href="{% url 'formentry:submit_tableindex' formid=formid tid=member.id %}" class="btn btn-primary" order={{member.weight}}>{{member.id}}.{{member}}</a>
    {% endif %}
    {% if ques_type %}
    <a href="{% url 'formentry:submit_questionindex' tid=tid qid=member.id %}" class="btn btn-primary" order={{member.weight}}>{{member.id}}.{{member}}</a>
    {% endif %}
    {% if choice_type %}
    <a href="{% url 'formentry:submit_choiceindex' qid=qid cid=member.id %}" class="btn btn-primary" order={{member.weight}}>{{member.id}}.{{member}}</a>
  {% endif %}</div>
  {% endfor %}
</div>
<script type="text/javascript">
var el = document.getElementById('A')
var mysortable =
  Sortable.create(el, {
  animation: 200,
  group: {
    name: "shared",
    pull: "clone",
    revertClone: true,
  },
  sort: true
  });

</script>
{% endblock %}

{% block form-footer %}

{% endblock %}

{% block form-nav %}
{% if new %}
<a class="btn btn-primary" href="{{new}}">नयाँ बनाउनुहोस्</a>
{% endif %}
<a class="btn btn-danger" href="/forms/design/">सबै फारम हेर्नुहोस् । </a>
{% endblock %}

django/parbatcms/formentry/templates/base_forms/listdeleteforms.html
{% extends 'entry_forms/user_forms.html' %}
{% load widget_tweaks %}
{% block form-title %}
  <h4 class="card-title">फ्याक्नपर्ने फारमहरु</h4>
  <p class="card-category">यी फारमहरु हेर्नको लागि मात्र हो ।</p>
{% endblock %}

{% block form-body %}
{% for forms in allforms %}
{% with mytype=forms.formType   %}
<p><a href="{% url 'formentry:deleteforms' form_id=forms.id %}" class="btn btn-primary">{{forms}} : Type {{mytype}}</a></p>
{% endwith %}
{% endfor %}
{% endblock %}
{% block form-footer %}

{% endblock %}

{% block form-nav %}
{% if next %}
<a class="btn btn-primary" href="{{next}}">Next</a>
{% endif %}
{% if back %}
<p><a class="btn btn-primary" href="{{back}}">पछाडी</a></p>
{% endif %}
{% if new %}
<a class="btn btn-primary" href="{{new}}">अर्को थप्नुहोस् ।</a>
{% endif %}
<a class="btn btn-danger" href="{% url 'formentry:all_my_forms' %}">सबै फारम हेर्नुहोस् । </a>
{% endblock %}

django/parbatcms/formentry/templates/base_forms/listprintforms.html
{% extends 'entry_forms/user_forms.html' %}
{% load widget_tweaks %}
{% block form-title %}
  <h4 class="card-title">सबै फारमहरु</h4>
  <p class="card-category">यी फारमहरु हेर्नको लागि मात्र हो ।</p>
{% endblock %}

{% block form-body %}
{% for forms in allforms %}
{% with mytype=forms.formType   %}
<p><a href="{% url 'formentry:form_basic' form_id=forms.id member=member mark=mark marker=marker %}" class="btn btn-primary">{{forms}} : Type {{mytype}}</a></p>
{% endwith %}
{% endfor %}
{% endblock %}
{% block form-footer %}

{% endblock %}

{% block form-nav %}
{% if next %}
<a class="btn btn-primary" href="{{next}}">Next</a>
{% endif %}
{% if back %}
<p><a class="btn btn-primary" href="{{back}}">पछाडी</a></p>
{% endif %}
{% if new %}
<a class="btn btn-primary" href="{{new}}">अर्को थप्नुहोस् ।</a>
{% endif %}
<a class="btn btn-danger" href="{% url 'formentry:print_my_forms' %}">सबै फारम हेर्नुहोस् । </a>
{% endblock %}

django/parbatcms/formentry/templates/base_forms/mytemplate.html
{% extends 'entry_forms/user_forms.html' %}
{% load widget_tweaks %}
{% block form-title %}
  <h4 class="card-title">सबै फारमहरु</h4>
  <p class="card-category">यी फारमहरु हेर्नको लागि मात्र हो ।</p>
{% endblock %}

{% block form-body %}
<form action="{% url 'postform:saveposts' %}" method="post">
{% if marks %}
<h3>Self Marks : {{obtained_marks.own}}</h3>
<h3>Ward Marks : {{obtained_marks.ward}}</h3>
{% endif %}
<input type="submit" value="Submit पेश गर्नुहोस् । " class='btn btn-danger' style="width:100%"/>
{% for qna, ans, choice, marks  in field_choices %}
<div class="form-group row">
  <div class="col-md-8">
    <h4>{{qna}}</h4><input type="hidden" value="{{qna.id}}" name="questions[]"/>
    <p>{{choice}}</p><input type="hidden" value="{{ans}}" name="answers[]"/>
  </div>
  <div class="col-md-4 form-group row">
    {% for i,j in marks.items %}
      {% for k in j %}
        <label style="text-align:right; font-size:12px; text-transform:none;" class="col-xs-6 col-form-label">मूल्याङ्कन</label>
        <div class="col-xs-6">
          <input name="mark{{forloop.counter}}[]" type="number" size="4" style="width:80px" value="{{k}}"/>
        </div>
      {% endfor %}
    {% endfor %}
  </div>
</div>
{% endfor %}
{% csrf_token %}
<input type="hidden" name="formid" value="{{form.id}}"/>
<input type="hidden" name = "member" value="{{member}}"/>
<input type="submit" value="Submit पेश गर्नुहोस् । " class='btn btn-danger' style="width:100%"/>
</form>

{% endblock %}

{% block form-footer %}

{% endblock %}

{% block form-nav %}

{% endblock %}

django/parbatcms/formentry/templates/base_forms/print_form.html
  <h4 class="card-title">{{form.formName}}</h4>
  <p class="card-category">जम्मा प्रश्नकर्ता सङ्ख्या =‍ {{form.markers}}</p>





{% for tables in formquestions %}
<table>
  <td colspan="2"><strong>{{tables.table.tableName}}</strong></td>
  {% if tables.table_questions %}{% else %}
  Sorry, No questions are added for this table
  {% endif %}
  {% for one_question in tables.table_questions %}
    <tr>
      <td style="text-align:right; font-size:18px; text-transform:none;" for="{{one_question.question.id}}" class="col-md-6 col-form-label"><p style="color:red;">{{one_question.question}} {% if mark >= 1 %}</p><p> अङ्क भार: {{one_question.question.marks}} {% endif %}</p></td>
      <td>
          {% if one_question.question.answerType == 'sc' %}

            {% for choices in one_question.choice %}
              {{choices}},
            {% endfor %}

          {% elif one_question.question.answerType == 'yn'  %}
          छ (हो),छैन (होइन)

          {% else %}
            लेख्नुपर्ने
          {% endif %}
      </td>
    </tr>



  {% endfor %}
</table>
{% endfor %}